/* Generated by tools/optimize-gallery.py. Re-run it after adding photos. */
const gallerySections = [
 {
  "id": "notebooks",
  "title": "The <i>Notebooks</i>",
  "note": "Project Rupaantar",
  "layout": "natural",
  "items": [
   {
    "thumb": "images/gallery/opt/notebooks-rupa-1-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-1-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Warli Art Notebook",
    "meta": "",
    "alt": "Warli Art Notebook"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-2-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-2-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "The Rupaantar Notebook",
    "meta": "",
    "alt": "The Rupaantar Notebook"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-3-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-3-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Peacock Art (NMIMS edition)",
    "meta": "",
    "alt": "Peacock Art (NMIMS edition)"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-4-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-4-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Peacock, Second Angle",
    "meta": "",
    "alt": "Peacock, Second Angle"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-5-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-5-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Mandala Notebook",
    "meta": "Rupaantar x Enactus MPSTME",
    "alt": "Mandala Notebook"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-6-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-6-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Wrapped & Ready",
    "meta": "",
    "alt": "Wrapped & Ready"
   }
  ]
 },
 {
  "id": "team",
  "title": "Our <i>Team</i>",
  "note": "Enactus MPSTME",
  "layout": "portrait",
  "items": [
   {
    "thumb": "images/gallery/opt/team-aditi-thumb.webp",
    "full": "images/gallery/opt/team-aditi-full.webp",
    "w": 640,
    "h": 681,
    "caption": "Aditi",
    "meta": "",
    "alt": "Aditi"
   },
   {
    "thumb": "images/gallery/opt/team-aditiya-thumb.webp",
    "full": "images/gallery/opt/team-aditiya-full.webp",
    "w": 412,
    "h": 532,
    "caption": "Aditiya",
    "meta": "",
    "alt": "Aditiya"
   },
   {
    "thumb": "images/gallery/opt/team-ayush-thumb.webp",
    "full": "images/gallery/opt/team-ayush-full.webp",
    "w": 523,
    "h": 378,
    "caption": "Ayush",
    "meta": "",
    "alt": "Ayush"
   },
   {
    "thumb": "images/gallery/opt/team-balmukund-thumb.webp",
    "full": "images/gallery/opt/team-balmukund-full.webp",
    "w": 640,
    "h": 549,
    "caption": "Balmukund",
    "meta": "",
    "alt": "Balmukund"
   },
   {
    "thumb": "images/gallery/opt/team-kanishka-thumb.webp",
    "full": "images/gallery/opt/team-kanishka-full.webp",
    "w": 640,
    "h": 443,
    "caption": "Kanishka",
    "meta": "",
    "alt": "Kanishka"
   },
   {
    "thumb": "images/gallery/opt/team-manya-thumb.webp",
    "full": "images/gallery/opt/team-manya-full.webp",
    "w": 640,
    "h": 660,
    "caption": "Manya",
    "meta": "",
    "alt": "Manya"
   },
   {
    "thumb": "images/gallery/opt/team-member1-thumb.webp",
    "full": "images/gallery/opt/team-member1-full.webp",
    "w": 640,
    "h": 960,
    "caption": "Member1",
    "meta": "",
    "alt": "Member1"
   },
   {
    "thumb": "images/gallery/opt/team-member2-thumb.webp",
    "full": "images/gallery/opt/team-member2-full.webp",
    "w": 592,
    "h": 1600,
    "caption": "Member2",
    "meta": "",
    "alt": "Member2"
   },
   {
    "thumb": "images/gallery/opt/team-member3-thumb.webp",
    "full": "images/gallery/opt/team-member3-full.webp",
    "w": 640,
    "h": 886,
    "caption": "Member3",
    "meta": "",
    "alt": "Member3"
   },
   {
    "thumb": "images/gallery/opt/team-member4-thumb.webp",
    "full": "images/gallery/opt/team-member4-full.webp",
    "w": 640,
    "h": 764,
    "caption": "Member4",
    "meta": "",
    "alt": "Member4"
   },
   {
    "thumb": "images/gallery/opt/team-member5-thumb.webp",
    "full": "images/gallery/opt/team-member5-full.webp",
    "w": 640,
    "h": 960,
    "caption": "Member5",
    "meta": "",
    "alt": "Member5"
   },
   {
    "thumb": "images/gallery/opt/team-parv-thumb.webp",
    "full": "images/gallery/opt/team-parv-full.webp",
    "w": 593,
    "h": 546,
    "caption": "Parv",
    "meta": "",
    "alt": "Parv"
   },
   {
    "thumb": "images/gallery/opt/team-sid-thumb.webp",
    "full": "images/gallery/opt/team-sid-full.webp",
    "w": 372,
    "h": 380,
    "caption": "Sid",
    "meta": "",
    "alt": "Sid"
   },
   {
    "thumb": "images/gallery/opt/team-siddi-thumb.webp",
    "full": "images/gallery/opt/team-siddi-full.webp",
    "w": 232,
    "h": 292,
    "caption": "Siddi",
    "meta": "",
    "alt": "Siddi"
   }
  ]
 }
];
