/* Generated by tools/optimize-gallery.py. Re-run it after adding photos. */
const gallerySections = [
 {
  "id": "parichay",
  "title": "",
  "note": "",
  "layout": "natural",
  "items": [
   {
    "thumb": "images/gallery/opt/parichay-team-1-thumb.webp",
    "full": "images/gallery/opt/parichay-team-1-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-2-thumb.webp",
    "full": "images/gallery/opt/parichay-team-2-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-3-thumb.webp",
    "full": "images/gallery/opt/parichay-team-3-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-4-thumb.webp",
    "full": "images/gallery/opt/parichay-team-4-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-5-thumb.webp",
    "full": "images/gallery/opt/parichay-team-5-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-6-thumb.webp",
    "full": "images/gallery/opt/parichay-team-6-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-7-thumb.webp",
    "full": "images/gallery/opt/parichay-team-7-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-8-thumb.webp",
    "full": "images/gallery/opt/parichay-team-8-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   }
  ]
 },
 {
  "id": "GBM",
  "title": "<i>GBM</i>",
  "note": "First meeting of this year with the new incoming execs.",
  "layout": "natural",
  "items": [
   {
    "thumb": "images/gallery/opt/GBM-IMG_20260808_171429-thumb.webp",
    "full": "images/gallery/opt/GBM-IMG_20260808_171429-full.webp",
    "w": 640,
    "h": 287,
    "caption": "GBM",
    "meta": "",
    "alt": "GBM"
   },
   {
    "thumb": "images/gallery/opt/GBM-IMG_8691-thumb.webp",
    "full": "images/gallery/opt/GBM-IMG_8691-full.webp",
    "w": 640,
    "h": 427,
    "caption": "GBM",
    "meta": "",
    "alt": "GBM"
   },
   {
    "thumb": "images/gallery/opt/GBM-IMG-20260808-WA0028-thumb.webp",
    "full": "images/gallery/opt/GBM-IMG-20260808-WA0028-full.webp",
    "w": 640,
    "h": 853,
    "caption": "IMG 20260808 WA0028",
    "meta": "",
    "alt": "IMG 20260808 WA0028"
   },
   {
    "thumb": "images/gallery/opt/GBM-20260808_182922-thumb.webp",
    "full": "images/gallery/opt/GBM-20260808_182922-full.webp",
    "w": 640,
    "h": 360,
    "caption": "GBM",
    "meta": "",
    "alt": "GBM"
   },
   {
    "thumb": "images/gallery/opt/GBM-IMG_8697-thumb.webp",
    "full": "images/gallery/opt/GBM-IMG_8697-full.webp",
    "w": 640,
    "h": 427,
    "caption": "GBM",
    "meta": "",
    "alt": "GBM"
   },
   {
    "thumb": "images/gallery/opt/GBM-IMG_8708-thumb.webp",
    "full": "images/gallery/opt/GBM-IMG_8708-full.webp",
    "w": 640,
    "h": 427,
    "caption": "GBM",
    "meta": "",
    "alt": "GBM"
   },
   {
    "thumb": "images/gallery/opt/GBM-IMG_8713-thumb.webp",
    "full": "images/gallery/opt/GBM-IMG_8713-full.webp",
    "w": 640,
    "h": 427,
    "caption": "GBM",
    "meta": "",
    "alt": "GBM"
   },
   {
    "thumb": "images/gallery/opt/GBM-IMG_8717-thumb.webp",
    "full": "images/gallery/opt/GBM-IMG_8717-full.webp",
    "w": 640,
    "h": 427,
    "caption": "GBM",
    "meta": "",
    "alt": "GBM"
   }
  ]
 }
];
