/* Generated by tools/optimize-gallery.py. Re-run it after adding photos. */
const gallerySections = [
 {
  "id": "parichay",
  "title": "",
  "note": "",
  "layout": "natural",
  "items": [
   {
    "thumb": "images/gallery/opt/parichay-team-1-thumb.webp",
    "full": "images/gallery/opt/parichay-team-1-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-2-thumb.webp",
    "full": "images/gallery/opt/parichay-team-2-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-3-thumb.webp",
    "full": "images/gallery/opt/parichay-team-3-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-4-thumb.webp",
    "full": "images/gallery/opt/parichay-team-4-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-5-thumb.webp",
    "full": "images/gallery/opt/parichay-team-5-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-6-thumb.webp",
    "full": "images/gallery/opt/parichay-team-6-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-7-thumb.webp",
    "full": "images/gallery/opt/parichay-team-7-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   },
   {
    "thumb": "images/gallery/opt/parichay-team-8-thumb.webp",
    "full": "images/gallery/opt/parichay-team-8-full.webp",
    "w": 640,
    "h": 480,
    "caption": "",
    "meta": "",
    "alt": ""
   }
  ]
 },
 {
  "id": "notebooks",
  "title": "The <i>Notebooks</i>",
  "note": "Project Rupaantar",
  "layout": "natural",
  "items": [
   {
    "thumb": "images/gallery/opt/notebooks-rupa-1-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-1-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Warli Art Notebook",
    "meta": "",
    "alt": "Warli Art Notebook"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-2-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-2-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "The Rupaantar Notebook",
    "meta": "",
    "alt": "The Rupaantar Notebook"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-3-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-3-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Peacock Art (NMIMS edition)",
    "meta": "",
    "alt": "Peacock Art (NMIMS edition)"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-4-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-4-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Peacock, Second Angle",
    "meta": "",
    "alt": "Peacock, Second Angle"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-5-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-5-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Mandala Notebook",
    "meta": "Rupaantar x Enactus MPSTME",
    "alt": "Mandala Notebook"
   },
   {
    "thumb": "images/gallery/opt/notebooks-rupa-6-thumb.webp",
    "full": "images/gallery/opt/notebooks-rupa-6-full.webp",
    "w": 640,
    "h": 1386,
    "caption": "Wrapped & Ready",
    "meta": "",
    "alt": "Wrapped & Ready"
   }
  ]
 }
];
