#!/usr/bin/env python3
"""Optimize gallery photos and (re)generate gallery-data.js.

Run from repo root:  python3 tools/optimize-gallery.py
Needs:               pip install Pillow

Reads   images/rupa-product-1..6.jpeg  (notebooks, fixed captions)
        images/gallery/{notebooks,shilpkaar,team,moments}/*
Writes  images/gallery/opt/<id>-<name>-thumb.webp  (640px wide)
        images/gallery/opt/<id>-<name>-full.webp   (1400px wide)
        gallery-data.js  (real w/h of each thumb, empty sections skipped)
Originals are never referenced by the page.
"""
import json, re
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
GAL = ROOT / 'images' / 'gallery'
OPT = GAL / 'opt'
EXT = {'.jpg', '.jpeg', '.png', '.webp'}

SECTIONS = [
    dict(id='parichay', folder='parichay', title='',
         note='',
         layout='natural', default=''),
    dict(id='GBM', folder='GBM', title='<i>GBM</i>', note='First meeting of this year with the new incoming execs.',
         layout='natural', default='GBM'),
    dict(id='shilpkaar', folder='shilpkaar', title='<i>Shilpkaar</i>', note='Project Shilpkaar',
         layout='natural', default='Shilpkaar'),
    dict(id='moments', folder='moments', title='<i>Moments</i>', note='Trips and events',
         layout='natural', default='Moment'),
]



CAMERA = re.compile(r'^(img|dsc|pxl|photo|wa|screenshot|image|team)?[-_ ]*[\d_\-\s]*$', re.I)

def caption_from(stem, default):
    if CAMERA.match(stem):
        return default
    s = re.sub(r'[-_]+', ' ', stem).strip()
    return s[:1].upper() + s[1:]

def save(src, key):
    im = ImageOps.exif_transpose(Image.open(src))
    if im.mode not in ('RGB', 'L'):
        im = im.convert('RGB')
    out = {}
    for tag, width, q in (('thumb', 640, 78), ('full', 1400, 80)):
        w = min(width, im.width)                      # never upscale
        h = round(im.height * w / im.width)
        p = OPT / f'{key}-{tag}.webp'
        im.resize((w, h), Image.LANCZOS).save(p, 'WEBP', quality=q, method=6)
        out[tag] = (p.relative_to(ROOT).as_posix(), w, h)
    return out

def item(paths, caption, meta):
    t, f = paths['thumb'], paths['full']
    return dict(thumb=t[0], full=f[0], w=t[1], h=t[2], caption=caption, meta=meta, alt=caption)

def main():
    OPT.mkdir(parents=True, exist_ok=True)
    result, total = [], 0
    for sec in SECTIONS:
        items = []

        folder = GAL / sec['folder']
        if folder.is_dir():
            for src in sorted(folder.iterdir()):
                if src.suffix.lower() in EXT:
                    cap = caption_from(src.stem, sec['default'])
                    items.append(item(save(src, f"{sec['id']}-{src.stem}"), cap, ''))
        if not items:
            print(f"skip  {sec['id']} (no photos)")
            continue
        print(f"ok    {sec['id']}: {len(items)} photos")
        total += sum((ROOT / it['thumb']).stat().st_size for it in items)
        result.append(dict(id=sec['id'], title=sec['title'], note=sec['note'],
                           layout=sec['layout'], items=items))
    (ROOT / 'gallery-data.js').write_text(
        '/* Generated by tools/optimize-gallery.py. Re-run it after adding photos. */\n'
        'const gallerySections = ' + json.dumps(result, indent=1, ensure_ascii=False) + ';\n',
        encoding='utf-8')
    print(f'thumbs total: {total/1024/1024:.2f} MB')

if __name__ == '__main__':
    main()
